version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: npu.postgres
    hostname: npu.postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: NpuBackend.Api/Dockerfile
    container_name: npu.api
    hostname: npu.api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__PostgreSQL: "Host={DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};"
    ports:
      - "5000:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
